[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyMeterBus"
dynamic = ["version"]
description = "Python implementation of the Meter-Bus protocol"
authors = [
    { name = "Mikael Ganehag Brorsson", email = "mikael.brorsson@gmail.com" }
]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries"
]

[project.urls]
Homepage = "https://github.com/ganehag/pyMeterBus"

[project.scripts]
pymeterbus-decode = "meterbus.cli.decode:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["meterbus", "meterbus.*"]
exclude = ["tests", "tests.*", "examples"]

[tool.setuptools.dynamic]
version = { attr = "meterbus.__version__" }

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
